name: build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build on Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
          - 21

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install python-docutils
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-docutils

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew check distZip
